spring:
  datasource:
    url: jdbc:postgresql://192.168.0.148:5432/postgres
    username: postgres
    password: postgres00

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextul_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG
