spring:
  datasource:
    url: jdbc:postgresql://192.168.0.148:5432/postgres
    username: postgres
    password: postgres00
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
